### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by johanneskoester** [snakemake/snakemake-executor-plugin-azure-batch#5]
HI @jakevc, shall we release? Does the true API workflow run for you? https://github.com/snakemake/snakemake-executor-plugin-azure-batch/actions/workflows/ci_true_api.yml (there is a "run workflow" button for manually triggering it).

**Comment by jakevc** [comment]
Failing for me so far:

https://github.com/snakemake/snakemake-executor-plugin-azure-batch/actions/runs/7131551052

I can see the workflow tar file, but no evidence of test output files in minio: https://play.min.io:9443/browser/snakemake-0541a4b6e63e4ceb9b5c63f02fff0fdf

**Comment by jakevc** [comment]
@johanneskoester latest true run just failed with: 
```
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WorkflowError:
The following required arguments are missing for plugin s3: --storage-s3-access-key, --storage-s3-secret-key.
```

**Comment by johanneskoester** [comment]
Ah, this sounds like envvars are not properly passed to the batch job.

**Comment by johanneskoester** [comment]
Fix pushed

**Comment by jakevc** [comment]
🚀

**Comment by johanneskoester** [comment]
It worked!!! Release time!
